# -----------------------------------------------------------------------------
#
# This file is part of the xPack project (http://xpack.github.io).
# Copyright (c) 2025 Liviu Ionescu. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose is hereby granted, under the terms of the MIT license.
#
# If a copy of the license was not distributed with this file, it can
# be obtained from https://opensource.org/licenses/MIT.
#
# -----------------------------------------------------------------------------

  name: 'Test SourceForge downloads'

  on:
    schedule:
      - cron: '33 9 * * 6' # every Sunday
    workflow_dispatch:

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            repository: xpack-dev-tools/xbb-helper-xpack
            ref: 'xpack-development'

        - name: Show environment
          run: |
            ls -lLA
            env | sort | grep -E '^[^ \t]+='

        - name: Run test
          run: |
            #!/usr/bin/env bash
            set -e

            # The script is in the xbb-helper-xpack repo.
            source maintenance-scripts/download-sourceforge-source.sh

            date

            # https://sourceforge.net/projects/cmake-xpack/files/
            name="cmake"
            threshold=16383 # (50%)

            # 2025
            platforms="win32-x64,linux-x64,linux-arm64,darwin-x64,darwin-arm64"

            # 2024
            platforms="win32-x64,linux-x64,linux-arm64,linux-arm,darwin-x64,darwin-arm64"
            download_sourceforge "${name}" "3.30.7-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "3.29.9-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "3.28.6-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "3.27.9-1" ${threshold} "${platforms}"

            # 2023
            platforms="win32-x64,linux-x64,linux-arm64,linux-arm,darwin-x64,darwin-arm64"
            download_sourceforge "${name}" "3.26.5-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "3.25.3-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "3.24.4-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "3.23.5-1" ${threshold} "${platforms}"

            # 2022
            platforms="win32-x64,linux-x64,linux-arm64,linux-arm,darwin-x64,darwin-arm64"
            download_sourceforge "${name}" "3.22.6-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "3.21.6-1" ${threshold} "${platforms}"

            # 2021
            platforms="win32-x64,win32-ia32,linux-x64,linux-ia32,linux-arm64,linux-arm,darwin-x64"
            download_sourceforge "${name}" "3.20.6-2" ${threshold} "${platforms}"

            # 2020
            platforms="win32-x64,win32-ia32,linux-x64,linux-ia32,linux-arm64,linux-arm,darwin-x64"
            download_sourceforge "${name}" "3.19.8-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "3.19.2-2" ${threshold} "${platforms}"
            download_sourceforge "${name}" "3.18.6-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "3.19.1-1" ${threshold} "${platforms}"
            download_sourceforge "${name}" "3.18.5-1" ${threshold} "${platforms}"

            # 2019
            platforms="win32-x64,win32-x32,linux-x64,linux-x32,darwin-x64"
            download_sourceforge "${name}" "3.18.3-1" ${threshold} "${platforms}"
